### ISSUE TITLE
Add optiboot as an option and adjust max upload sizes?

### ISSUE THREAD

**Issue by benlye** [SkyNet3D/anet-board#1]
Would you be interested in a simple PR which would add an option for the Anet board with Optiboot bootloader, and adjusting the max upload size to leave room for the bootloader?

This is boards.txt the file I use:
https://github.com/benlye/anet-board/blob/benlye-anet-board/hardware/anet/avr/boards.txt

**Comment by oderwat** [comment]
Sure. Sounds good!
