### ISSUE TITLE
Anet A8 V1.5 board Denied

### ISSUE THREAD

**Issue by poorbullfrog** [SkyNet3D/anet-board#16]
I have been trying to update my A8 firmware to marlin. I can see the board in my device manager without errors. How ever I keep getting this error message. Please help.
avrdude: ser_open(): can't open device "\\.\COM4": Access is denied.

**Comment by DoctorPunto** [comment]
I am having the same issue. this file is for the V1.0 versions of the board. Do we know if there is a v1-5 in the works?
avrdude: ser_open(): can't open device "\\.\COM5": Access is denied.

**Comment by oderwat** [comment]
This should have nothing to do with the board. And there is no reason why it should not work anymore. I used it myself just some days ago. You may move on and use the unified firmware from th3d instead. I think it comes with a full arduino and board config also for the A8.

**Comment by oderwat** [comment]
Did you make sure that no other software is accessing the printer? Shut down your repetier-host, octoprint, cura, simplify 3d or whatever is being used with the printer. If all fails fall back to use an USBasp (programmer) instead of the bootloader. The bootloader may also be corrupted.

**Comment by poorbullfrog** [comment]
I double checked the device manager, the board is the only thing requesting a com port. Even when trying to burn a boot loader the request timed out. The com light on the anet board will blink intermittently then cancel out.

**Comment by poorbullfrog** [comment]
Doctor punto: I was able to get past the access denied part by. Opening device manager clicking on view, select hidden/disconnected devices. Then right clicking on each listed under com port then removed and deleted drivers. I then used drivers from the sd card.

**Comment by poorbullfrog** [comment]
I got it to load marlin. Had to burn bootloader with a usbasp through a blank arduino ide. Then load marlin. But I’m still trying to get the settings figured out.
